In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torchattacks
from torchattacks import FGSM, PGD, MIFGSM 
import pandas as pd
from functions import encode_variable
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, recall_score
import torch.nn.functional as F
from pathlib import Path

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import torchattacks
from torchattacks import FGSM, PGD, MIFGSM 
import pandas as pd
from functions import encode_variable
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.metrics import accuracy_score, f1_score, recall_score
import torch.nn.functional as F
from pathlib import Path

In [3]:
class RealTabularMIFGSM(torchattacks.MIFGSM):
    def __init__(self, model, eps=0.03, alpha=0.007, steps=10, decay=1.0, mask=None, feature_min = None, feature_max = None):
        super().__init__(model, eps, alpha, steps, decay)
        self.loss = nn.CrossEntropyLoss()  
        self.mask = mask 
        self.feature_min = feature_min
        self.feature_max = feature_max
        
    def forward(self, images, labels):
        """Overrides MIFGSM for tabular data."""
        
        adv_images = images.clone().detach()
        adv_images.requires_grad = True 
        
        momentum = 0
        for _ in range(self.steps):
            outputs = self.model(adv_images)
            loss = self.loss(outputs, labels)

            grad = torch.autograd.grad(loss, adv_images, retain_graph=True, create_graph=True, allow_unused=True)[0]

            if grad is None:
                print("ERROR: Gradient is None! adv_images is not in the graph!")
                break  

            grad = grad / torch.mean(torch.abs(grad), dim=(1,), keepdim=True)
            grad = grad + momentum * self.decay
            momentum = grad

            perturbation = self.alpha * grad.sign()
            if self.mask is not None:
                perturbation = perturbation * self.mask  # Zero out protected features

            adv_images = adv_images + perturbation
            adv_images = torch.clamp(adv_images, min=self.feature_min, max=self.feature_max) 
    
        return adv_images

In [4]:
# Generating, training and testing surrogate model
class SurrogateModel(nn.Module):
    def __init__(self, input_dim):
        super(SurrogateModel, self).__init__()
        self.fc1 = nn.Linear(input_dim, 128) 
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 2)  # Binary classification (Normal vs. Anomalous)

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = torch.relu(self.fc2(x))
        return self.fc3(x)

def test_surrogate(model_surrogate, X_test, y_test, device):
    model_surrogate.eval()
    X_test, y_test = X_test.to(device), y_test.to(device)

    with torch.no_grad():
        y_pred = model_surrogate(X_test).argmax(axis=1).cpu().numpy()

    accuracy = accuracy_score(y_test.cpu().numpy(), y_pred)
    recall = recall_score(y_test.cpu().numpy(), y_pred)
    f1 = f1_score(y_test.cpu().numpy(), y_pred, average='weighted')

    results = {
        "Accuracy": accuracy,
        "Recall": recall,
        "F1 Score": f1
    }
    print(f"Surrogate Model Results: {results}")
    return results

def train_surrogate(X_train, y_train, device):
    input_dim = X_train.shape[1]
    model_surrogate = SurrogateModel(input_dim).to(device)
    optimizer = optim.Adam(model_surrogate.parameters(), lr=0.001)
    criterion = nn.CrossEntropyLoss()

    train_loader = DataLoader(TensorDataset(X_train, y_train), batch_size=32, shuffle=True)

    for epoch in range(8):  # epochs
        for X_batch, y_batch in train_loader:
            X_batch, y_batch = X_batch.to(device), y_batch.to(device)
            optimizer.zero_grad()
            outputs = model_surrogate(X_batch)
            loss = criterion(outputs, y_batch)
            loss.backward()
            optimizer.step()
        print(f"Epoch {epoch+1}, Loss: {loss.item():.4f}")

    print("Surrogate model training complete.")
    return model_surrogate

In [ ]:
def process_data(input_data, device):
    data = input_data.dropna(axis=0)
    print(data)
    #print(data.nunique() > 1)
    #data = data.loc[:, data.nunique() > 1]
    data.columns = [col.strip().lower() for col in data.columns]
    new_cols = ['timestamp' if 'starttimestamp' in col else col for col in data.columns]
    data.columns = new_cols
    try:
        data['timestamp'] = pd.to_datetime(data['timestamp'], errors='coerce')
        data = data.sort_values(by='timestamp', ascending=True)
    except:
        print("timestamp fallido")
    features = [col for col in data.columns if col not in ['city', 'timestamp', 'anomaly', 'normal/attack',  'startdate', 'weekdaystart', 'yearstart', 'hourstart', 'minutestart', 'enddate', 'endtimestamp', 'weekdayend', 'yearend', 'hourend', 'minuteend', 'class']]
    if "connectortype" in [col for col in data.columns]:
        features = ['connectortype', 'durationcharge' , 'durationsession' , 'energy' , 'tariff' ,
                'cost' , 'meanpower', 'maxpower']
        data = encode_variable(data, data.columns.get_loc("connectortype"))

    for feature in features:
        data[feature] = pd.to_numeric(data[feature], errors='coerce')

    data.dropna()
    #data = data.sample(frac=1).reset_index(drop=True)
    x_data = data.loc[:, features].select_dtypes(include=[np.number])
    y_data = data.loc[:, ['anomaly']].values.ravel()
    print(y_data)

    size = len(x_data)
    size_init = int(size * 0.8)
    x_train = x_data[:size_init]
    y_train = y_data[:size_init]
    x_test = x_data[size_init:]
    y_test = y_data[size_init:]

    #x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.3, random_state=42, stratify=y_data)

    df = pd.DataFrame(x_test, columns=features)
    df["anomaly"] = y_test
    df = df.sample(frac=1).reset_index(drop=True)
    x_test = df.loc[:, features].values
    y_test = df.loc[:, ['anomaly']].values.ravel()
    x_train = np.array(x_train, dtype=np.float32) 
    x_test = np.array(x_test, dtype=np.float32)
    x_train = torch.tensor(x_train, dtype=torch.float32).to(device)
    y_train = torch.tensor(y_train, dtype=torch.long).to(device)
    x_test = torch.tensor(x_test, dtype=torch.float32).to(device)
    y_test = torch.tensor(y_test, dtype=torch.long).to(device)

    return data, x_train, x_test, y_train, y_test, features
			
def load_anomalous_test_samples(x_test, y_test):
    anomalous_indices = np.where(y_test == 1)[0] 
    X_anomalous = x_test[anomalous_indices]
    y_anomalous = y_test[anomalous_indices]
    return X_anomalous, y_anomalous, anomalous_indices

def process_anomalous_samples(x_train, y_train, x_test, y_test, device):
    # Prepare anomalous x y for perturbation
    X_anomalous_test, y_anomalous_test, anomalous_indices_test = load_anomalous_test_samples(x_test, y_test)
    X_anomalous_train, y_anomalous_train, anomalous_indices_train = load_anomalous_test_samples(x_train, y_train)
    x_anom_train = torch.tensor(X_anomalous_train, dtype=torch.float32).clone().detach().requires_grad_(True).to(device)
    x_anom_train = torch.tensor(X_anomalous_train, dtype=torch.float32).to(device)
    x_anom_train.requires_grad = True
    y_anom_train = torch.tensor(y_anomalous_train, dtype=torch.long).to(device)
    y_anom_train = y_anom_train.view(-1).to(device)
    
    x_anom_test = torch.tensor(X_anomalous_test, dtype=torch.float32).clone().detach().requires_grad_(True).to(device)
    x_anom_test = torch.tensor(X_anomalous_test, dtype=torch.float32).to(device)
    x_anom_test.requires_grad = True
    y_anom_test = torch.tensor(y_anomalous_test, dtype=torch.long).to(device)
    y_anom_test = y_anom_test.view(-1).to(device)

    return x_anom_train, y_anom_train, x_anom_test, y_anom_test, anomalous_indices_test, anomalous_indices_train

def extract_column_stats(df):
    stats = {}
    feature_min = []
    feature_max = []
    for column in df.columns:
        stats[column] = {
            'max': df[column].max(),
            'min': df[column].min(),
            'mean': df[column].mean()
        }
        feature_min.append(df[column].min())
        feature_max.append(df[column].max())
    print(stats)
    print(feature_min)
    print(feature_max)
    return stats, feature_min, feature_max

def generateMask(x): 
    mask = []
    for i in range(x.cpu().numpy().shape[1]):  
        col = x.cpu().numpy()[:, i] 
        unique_values = np.unique(col)  
        if len(unique_values) < 5 or np.issubdtype(col.dtype, np.integer):
            mask.append(0) 
        else:
            mask.append(1)
    print(mask)
    return mask

def save_samples_csv(adversarial_samples, adv_dir, data, features, y):
    adversarial_dataset = pd.DataFrame(adversarial_samples.detach().cpu().numpy(), columns=data.loc[:, features].columns)
    adversarial_dataset['anomaly'] = y.detach().cpu().numpy()
    adversarial_dataset.to_csv(adv_dir, index=False)
    #print(f"{adv_dir} converted to CSV")

def performAttacks(steps, x, y, mask, feature_min, feature_max, model_surrogate, file, stage, data, features, eps, alpha):
    mifgsm = RealTabularMIFGSM(model_surrogate, eps=eps, alpha=alpha, steps=steps, decay=0.8, mask=mask, feature_min=feature_min,
                                    feature_max=feature_max)
    mifgsm_samples = mifgsm(x, y)
    adv_dir = f'./data/aexamples/{file}/mifgsm/{stage}/adversarialexamples_eps{str(eps)}.csv'
    Path(adv_dir).parent.mkdir(parents=True, exist_ok=True)
    save_samples_csv(mifgsm_samples, adv_dir, data, features, y)

def attack(x, y, mask, feature_min, feature_max, model_surrogate, file, stage, data, features):
    steps = 20
    epsilons = [0.0]
     
    for value in np.arange(0.003, 0.031, 0.006):
        eps = round(value, 3)
        alpha = round(eps/steps, 4)
        performAttacks(steps, x, y, mask, feature_min, feature_max, model_surrogate, file, stage, data, features, eps, alpha)
        epsilons.append(eps)
    for value in np.arange(0.03, 0.3, 0.06):
        eps = round(value, 3)
        alpha = round(eps/steps, 4)
        performAttacks(steps, x, y, mask, feature_min, feature_max, model_surrogate, file, stage, data, features, eps, alpha)
        epsilons.append(eps)
    if "train" in stage:
        for value in np.arange(0.003, 0.3, 0.05):
            eps = round(value, 3)
            alpha = round(eps/steps, 4)
            performAttacks(steps, x, y, mask, feature_min, feature_max, model_surrogate, file, stage, data, features, eps, alpha)

    return epsilons

In [7]:
def generate_ae_examples():
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f'Device: {device}')
    data_path = Path('./data')
    original_results = {}
    files = [f for f in data_path.iterdir() if f.is_file()]
    for file in files:
        file_name = file.with_suffix('').as_posix().split('/')[1]
        original_results[file_name] = {}
        print(f"Processing file {file_name}")
        if 'xlsx' in file.name:
            data = pd.read_excel(file)
        else:
            data = pd.read_csv(file)
        data, x_train, x_test, y_train, y_test, features = process_data(data, device)
        print(np.unique(y_train.cpu().numpy(), return_counts=True))
        print(np.unique(y_test.cpu().numpy(), return_counts=True))
        # Train and test surrogate model
        model_surrogate = train_surrogate(x_train, y_train, device)
        original_results[file_name]['results'] = test_surrogate(model_surrogate, x_test, y_test, device)
        original_results[file_name]['x_test'] = x_test
        original_results[file_name]['y_test'] = y_test
        original_results[file_name]['x_train'] = x_train
        original_results[file_name]['y_train'] = y_train
        original_results[file_name]['features'] = features
        original_results[file_name]['model_surrogate'] = model_surrogate 
        # Generate data constraints
        stats, feature_min, feature_max = extract_column_stats(data.loc[:, features])
        mask = generateMask(x_train)
        feature_min = torch.tensor(np.array(feature_min), dtype=torch.float32).to(device)
        feature_max = torch.tensor(np.array(feature_max), dtype=torch.float32).to(device)  
        mask = torch.tensor(np.array(mask), dtype=torch.float32).to(device) 

        x_anom_train, y_anom_train, x_anom_test, y_anom_test, anomalous_indices_test, anomalous_indices_train = process_anomalous_samples(x_train.cpu(), y_train.cpu(), x_test.cpu(), y_test.cpu(), device)
        original_results[file_name]['anomalous_indices_test'] = anomalous_indices_test
        original_results[file_name]['anomalous_indices_train'] = anomalous_indices_train
        epsilons = attack(x_anom_train, y_anom_train, mask, feature_min, feature_max, model_surrogate, file_name, 'train', data, features)
        epsilons = attack(x_anom_test, y_anom_test, mask, feature_min, feature_max, model_surrogate, file_name, 'test', data, features)

    return original_results, epsilons, device
        
original_results, epsilons, device = generate_ae_examples()

Device: cuda
Processing file US_Alabama_clean_WithAnomalies
            Timestamp         P         Q  anomaly
0       4/10/19 21:36  2.497251  0.653574      1.0
1       3/10/19 14:31  5.054901  2.872479      1.0
2       2/10/19 20:36  4.524378  2.513386      1.0
3       3/10/19 16:57  2.743485  1.507386      1.0
4        3/10/19 6:41 -1.512417  0.163565      1.0
...               ...       ...       ...      ...
349995   5/10/19 1:13  0.151000  0.267000      0.0
349996   5/10/19 1:13  0.151000  0.260000      0.0
349997   5/10/19 1:13  0.150000  0.266000      0.0
349998   5/10/19 1:13  0.152000  0.263000      0.0
349999   5/10/19 1:13  0.151000  0.262000      0.0

[350000 rows x 4 columns]
[0. 0. 0. ... 1. 0. 0.]
(array([0, 1]), array([223970,  56030]))
(array([0, 1]), array([56030, 13970]))
Epoch 1, Loss: 0.2906
Epoch 2, Loss: 0.0481
Epoch 3, Loss: 0.0828
Epoch 4, Loss: 0.1972
Epoch 5, Loss: 0.1164
Epoch 6, Loss: 0.1840
Epoch 7, Loss: 0.1843
Epoch 8, Loss: 0.1527
Surrogate model training complete.
Surrogate Model Results: {'Accuracy': 0.9347571428571428, 'Recall': 0.8137437365783823, 'F1 Score': 0.9341804467218099}
{'p': {'max': np.float64(16.56969071680917), 'min': np.float64(-9.40100467485407), 'mean': np.float64(1.8384059902870848)}, 'q': {'max': np.float64(8.343), 'min': np.float64(-2.808851942442552), 'mean': np.float64(0.7737293369400968)}}
[np.float64(-9.40100467485407), np.float64(-2.808851942442552)]
[np.float64(16.56969071680917), np.float64(8.343)]
[1, 1]
Processing file Dundee_Clean_With_Anomalies_All
       country    city connectorType  durationCharge  durationSession  \
0           UK  Dundee         Rapid            0.16             0.17
1           UK  Dundee         Rapid            0.43             0.43
2           UK  Dundee         Rapid            0.12             0.12
3           UK  Dundee         Rapid            0.17             0.17
4           UK  Dundee         Rapid            0.64             0.65
...        ...     ...           ...             ...              ...
210509      UK  Dundee         Rapid            0.12             0.12
210510      UK  Dundee   Ultra-Rapid            1.47             1.47
210511      UK  Dundee         Rapid            0.63             0.63
210512      UK  Dundee          Fast            0.85             0.85
210513      UK  Dundee         Rapid            1.02             3.04

         energy    tariff     cost  meanPower  maxPower  ... hourStart  \
0         0.340  0.000000   0.0000      2.125        50  ...        23
1         8.430  0.237343   2.0008     19.605        50  ...        23
2         3.080  0.332727   1.0248     25.667        50  ...        23
3         1.090  0.604404   0.6588      6.412        50  ...        23
4        18.790  0.207770   3.9040     29.359        50  ...        23
...         ...       ...      ...        ...       ...  ...       ...
210509    1.185  0.240000   1.0200     35.775        50  ...         7
210510  108.970  0.000000  12.6200     74.129       150  ...         8
210511   20.530  0.205611   4.2212    -19.965        50  ...        17
210512    3.260  0.000000   0.0000     11.154         7  ...        14
210513   24.447  0.170000   4.0400     23.968        50  ...        18

        minuteStart              endDate  endTimestamp  weekDayEnd  yearEnd  \
0                36  31/12/2021 23:46:00    1640990760           4     2021
1                35  01/01/2022 00:01:00    1640991660           5     2022
2                34  31/12/2021 23:41:00    1640990460           4     2021
3                25  31/12/2021 23:35:00    1640990100           4     2021
4                21  01/01/2022 00:00:00    1640991600           5     2022
...             ...                  ...           ...         ...      ...
210509           16  21/03/2021 07:23:00    1616307780           6     2021
210510            7  09/09/2021 09:35:35    1631172935           3     2021
210511           48  07/12/2021 18:26:00    1638897960           1     2021
210512           16  29/04/2018 15:07:00    1525007220           6     2018
210513           45  22/05/2021 19:46:00    1621705560           5     2021

       hourEnd  minuteEnd  anomaly                   class
0           23         46        0                  Normal
1            0          1        0                  Normal
2           23         41        0                  Normal
3           23         35        0                  Normal
4            0          0        0                  Normal
...        ...        ...      ...                     ...
210509       7         23        1           energyAnomaly
210510       9         35        1             costAnomaly
210511      18         26        1        meanPowerAnomaly
210512      15          7        1        meanPowerAnomaly
210513      19         46        1  durationSessionAnomaly

[210514 rows x 24 columns]
[0 0 0 ... 1 0 0]
(array([0, 1]), array([121282,  47129]))
(array([0, 1]), array([24801, 17302]))
Epoch 1, Loss: 0.1907
Epoch 2, Loss: 0.7232
Epoch 3, Loss: 0.0825
Epoch 4, Loss: 0.3067
Epoch 5, Loss: 0.1106
Epoch 6, Loss: 0.1787
Epoch 7, Loss: 0.2357
Epoch 8, Loss: 0.0585
Surrogate model training complete.
Surrogate Model Results: {'Accuracy': 0.8358549272023371, 'Recall': 0.6444919662466767, 'F1 Score': 0.8287547934631817}
{'connectortype': {'max': np.float64(3.0), 'min': np.float64(0.0), 'mean': np.float64(1.550029926750715)}, 'durationcharge': {'max': np.float64(1073.8), 'min': np.float64(-0.63), 'mean': np.float64(4.459754315627464)}, 'durationsession': {'max': np.float64(2279.24), 'min': np.float64(-0.67), 'mean': np.float64(4.524453908053621)}, 'energy': {'max': np.float64(72881.498), 'min': np.float64(-75.49), 'mean': np.float64(17.776871234217197)}, 'tariff': {'max': np.float64(76.0), 'min': np.float64(0.0), 'mean': np.float64(0.27000748121786444)}, 'cost': {'max': np.float64(1229.95), 'min': np.float64(-58.7), 'mean': np.float64(3.319131291980581)}, 'meanpower': {'max': np.float64(417309.5), 'min': np.float64(-374.133), 'mean': np.float64(24.856876754040112)}, 'maxpower': {'max': np.int64(150), 'min': np.int64(7), 'mean': np.float64(38.599618077657546)}}
[np.float64(0.0), np.float64(-0.63), np.float64(-0.67), np.float64(-75.49), np.float64(0.0), np.float64(-58.7), np.float64(-374.133), np.int64(7)]
[np.float64(3.0), np.float64(1073.8), np.float64(2279.24), np.float64(72881.498), np.float64(76.0), np.float64(1229.95), np.float64(417309.5), np.int64(150)]
[0, 1, 1, 1, 1, 1, 1, 0]
Processing file US_Alabama_clean_WithAnomalies_a2
            Timestamp      P      Q  anomaly
0       2/10/19 16:50  8.055  2.071      0.0
1       4/10/19 20:57  0.728  0.309      0.0
2       1/10/19 10:48  0.010 -0.130      1.0
3       7/10/19 13:47  5.691  2.345      0.0
4        9/10/19 7:19  0.686  0.396      0.0
...               ...    ...    ...      ...
695728  2/10/19 20:48  4.412  1.777      0.0
695729  7/10/19 21:25  0.895  0.239      0.0
695730  8/10/19 20:55  0.410 -0.170      1.0
695731  7/10/19 21:56  0.797  0.409      0.0
695732   9/10/19 3:47  0.335  0.345      0.0

[695733 rows x 4 columns]
[1. 1. 1. ... 0. 0. 0.]
(array([0, 1]), array([516851,  39735]))
(array([0, 1]), array([130181,   8966]))
Epoch 1, Loss: 0.0057
Epoch 2, Loss: 0.0426
Epoch 3, Loss: 0.0009
Epoch 4, Loss: 0.0072
Epoch 5, Loss: 0.0035
Epoch 6, Loss: 0.0083
Epoch 7, Loss: 0.0066
Epoch 8, Loss: 0.0052
Surrogate model training complete.
Surrogate Model Results: {'Accuracy': 0.9969816093771335, 'Recall': 0.9534909658710685, 'F1 Score': 0.9969483387659672}
{'p': {'max': np.float64(11.884), 'min': np.float64(-0.2), 'mean': np.float64(1.2622784803940592)}, 'q': {'max': np.float64(8.343), 'min': np.float64(-0.2), 'mean': np.float64(0.568764787641236)}}
[np.float64(-0.2), np.float64(-0.2)]
[np.float64(11.884), np.float64(8.343)]
[1, 1]
Processing file Germany_clean_WithAnomalies_a2
          Timestamp            P           Q  anomaly
0        1532260360  1070.819946  658.260010      0.0
1        1541838810   315.760010   48.830002      0.0
2        1541028310   598.150024   86.250000      0.0
3        1534742750   348.410004  118.230003      0.0
4        1542874930   372.209991  105.209999      0.0
...             ...          ...         ...      ...
1656285  1545054180   401.470001  185.429993      0.0
1656286  1535151270   391.130005 -121.970001      0.0
1656287  1538578800   529.869995  100.190002      0.0
1656288  1538573940   497.910004  131.009995      0.0
1656289  1535710310   800.549988  233.839996      0.0

[1656290 rows x 4 columns]
[1. 1. 1. ... 0. 0. 0.]
(array([0, 1]), array([1230818,   94214]))
(array([0, 1]), array([309562,  21696]))
Epoch 1, Loss: 0.0894
Epoch 2, Loss: 0.0061
Epoch 3, Loss: 0.0047
Epoch 4, Loss: 0.0096
Epoch 5, Loss: 0.4773
Epoch 6, Loss: 0.0078
Epoch 7, Loss: 0.0120
Epoch 8, Loss: 0.1700
Surrogate model training complete.
Surrogate Model Results: {'Accuracy': 0.9886825374783401, 'Recall': 0.8674870943952803, 'F1 Score': 0.9884272026835844}
{'p': {'max': np.float64(7131.0698242188), 'min': np.float64(-0.2), 'mean': np.float64(608.5783800745846)}, 'q': {'max': np.float64(2214.4699707031), 'min': np.float64(-230.47999572754), 'mean': np.float64(118.96335628643432)}}
[np.float64(-0.2), np.float64(-230.47999572754)]
[np.float64(7131.0698242188), np.float64(2214.4699707031)]
[1, 1]
Processing file Portugal_clean_WithAnomalies_a2
                      Timestamp         P         Q  anomaly
0       2017-01-02 01:11:07.836  0.009186  0.005096      0.0
1       2017-01-09 00:43:03.836  0.011047 -0.003448      0.0
2       2017-01-09 01:13:56.836  0.004669  0.002869      0.0
3       2017-01-06 21:19:36.836  0.009308  0.000336      0.0
4       2017-01-02 15:03:22.836  0.014404  0.001801      0.0
...                         ...       ...       ...      ...
642412  2017-01-04 00:21:47.836  0.012726 -0.001221      0.0
642413  2017-01-09 12:48:23.836  0.014862 -0.006073      0.0
642414  2017-01-02 08:41:47.836  0.005524  0.003662      0.0
642415  2017-01-02 04:45:11.836  0.012756 -0.004272      0.0
642416  2017-01-09 10:17:40.836  0.065247 -0.015564      0.0

[642417 rows x 4 columns]
[1. 1. 1. ... 0. 0. 0.]
(array([0, 1]), array([477357,  36576]))
(array([0, 1]), array([120151,   8333]))
Epoch 1, Loss: 0.0022
Epoch 2, Loss: 0.0010
Epoch 3, Loss: 0.0006
Epoch 4, Loss: 0.0040
Epoch 5, Loss: 0.0025
Epoch 6, Loss: 0.0061
Epoch 7, Loss: 0.0117
Epoch 8, Loss: 0.0018
Surrogate model training complete.
Surrogate Model Results: {'Accuracy': 0.9979919678714859, 'Recall': 0.9729989199567983, 'F1 Score': 0.997981067899651}
{'p': {'max': np.float64(0.216827392578125), 'min': np.float64(-0.2), 'mean': np.float64(0.010879942921417156)}, 'q': {'max': np.float64(0.007965087890625), 'min': np.float64(-0.052947998046875), 'mean': np.float64(-0.0034136447174304228)}}
[np.float64(-0.2), np.float64(-0.052947998046875)]
[np.float64(0.216827392578125), np.float64(0.007965087890625)]
[1, 1]
Processing file vancover_clean_WithAnomalies_a2
         Timestamp    P      Q  anomaly
0       1336340760  286   82.0      0.0
1       1345823400  473   71.0      0.0
2       1360013220  356   91.0      0.0
3       1340805120  308   76.0      0.0
4       1353819480  450   67.0      0.0
...            ...  ...    ...      ...
419629  1362787380  592  114.0      0.0
419630  1342294620  510   91.0      0.0
419631  1357008600  354   92.0      0.0
419632  1348582860  357   94.0      0.0
419633  1340488500  320   77.0      0.0

[419634 rows x 4 columns]
[1. 1. 1. ... 0. 0. 0.]
(array([0, 1]), array([311843,  23864]))
(array([0, 1]), array([78456,  5471]))
Epoch 1, Loss: 0.0986
Epoch 2, Loss: 0.2289
Epoch 3, Loss: 0.0235
Epoch 4, Loss: 0.1985
Epoch 5, Loss: 0.0068
Epoch 6, Loss: 0.0465
Epoch 7, Loss: 0.1211
Epoch 8, Loss: 0.0817
Surrogate model training complete.
Surrogate Model Results: {'Accuracy': 0.9549727739583209, 'Recall': 0.5997075488941692, 'F1 Score': 0.9537502259587803}
{'p': {'max': np.int64(9669), 'min': np.int64(2), 'mean': np.float64(882.8246614907276)}, 'q': {'max': np.float64(2201.0), 'min': np.float64(-0.2), 'mean': np.float64(113.29943681875159)}}
[np.int64(2), np.float64(-0.2)]
[np.int64(9669), np.float64(2201.0)]
[1, 1]
Processing file Germany_clean_WithAnomalies
         Timestamp            P           Q  anomaly
0       1528967290   314.063521  -66.012509      1.0
1       1527847930  1366.820660  265.063256      1.0
2       1527203290   603.973692  -67.402362      1.0
3       1527935810   585.019214  226.277813      1.0
4       1527566230   911.004787  -78.851127      1.0
...            ...          ...         ...      ...
349995  1529097130   595.690002  -21.510000      0.0
349996  1529097140   592.150024  -21.020000      0.0
349997  1529097150   595.250000  -20.110001      0.0
349998  1529097160   596.440002  -20.459999      0.0
349999  1529097170   595.059998  -19.969999      0.0

[350000 rows x 4 columns]
[0. 0. 0. ... 0. 0. 0.]
(array([0, 1]), array([223970,  56030]))
(array([0, 1]), array([56030, 13970]))
Epoch 1, Loss: 0.2520
Epoch 2, Loss: 0.4831
Epoch 3, Loss: 0.4666
Epoch 4, Loss: 0.4563
Epoch 5, Loss: 0.3700
Epoch 6, Loss: 0.4179
Epoch 7, Loss: 0.5416
Epoch 8, Loss: 0.3120
Surrogate model training complete.
Surrogate Model Results: {'Accuracy': 0.8605142857142857, 'Recall': 0.36800286327845383, 'F1 Score': 0.8376396249720253}
{'p': {'max': np.float64(6979.6201171875), 'min': np.float64(-1839.7743933255697), 'mean': np.float64(706.885477780142)}, 'q': {'max': np.float64(2358.3026447503225), 'min': np.float64(-681.9253534499458), 'mean': np.float64(123.13570544955016)}}
[np.float64(-1839.7743933255697), np.float64(-681.9253534499458)]
[np.float64(6979.6201171875), np.float64(2358.3026447503225)]
[1, 1]
Processing file Canada1_clean_WithAnomalies_a2
           Timestamp    P      Q  anomaly
0         1455338838   47   9.00      0.0
1         1455002525    0   0.00      0.0
2         1455084684  133  53.00      0.0
3         1455044684    0   0.00      0.0
4         1455464248    0   1.00      0.0
...              ...  ...    ...      ...
14929915  1455376976  112   7.49      1.0
14929916  1454949987   18   8.00      0.0
14929917  1455005506    0   0.00      0.0
14929918  1454889953    0   4.00      0.0
14929919  1455156184    1  -0.09      1.0

[14929920 rows x 4 columns]
[1. 1. 1. ... 0. 0. 0.]
(array([0, 1]), array([11094491,   849445]))
(array([0, 1]), array([2790321,  195663]))
Epoch 1, Loss: 0.2856
Epoch 2, Loss: 0.0562
Epoch 3, Loss: 0.0016
Epoch 4, Loss: 0.0785
Epoch 5, Loss: 0.0048
Epoch 6, Loss: 0.1840
Epoch 7, Loss: 0.0088
Epoch 8, Loss: 0.0155
Surrogate model training complete.
Surrogate Model Results: {'Accuracy': 0.978711540316358, 'Recall': 0.8556702084706869, 'F1 Score': 0.978887346098825}
{'p': {'max': np.int64(7118), 'min': np.int64(0), 'mean': np.float64(55.59795564879115)}, 'q': {'max': np.float64(4486.0), 'min': np.float64(-0.2), 'mean': np.float64(11.444592052067247)}}
[np.int64(0), np.float64(-0.2)]
[np.int64(7118), np.float64(4486.0)]
[1, 1]
Processing file Netherlands_Clean_With_Anomalies
           country city connectorType  durationCharge  durationSession  \
0      Netherlands    -          Fast            2.24             2.27
1      Netherlands    -          Fast            5.11             5.11
2      Netherlands    -          Fast            1.56             1.69
3      Netherlands    -          Fast            2.77             2.77
4      Netherlands    -          Fast            5.34             6.50
...            ...  ...           ...             ...              ...
12363  Netherlands    -          Fast            2.00             1.03
12364  Netherlands    -          Fast            2.53             1.00
12365  Netherlands    -          Fast            4.00            12.74
12366  Netherlands    -          Fast            1.51             4.35
12367  Netherlands    -          Fast            5.13             8.03

       energy  tariff   cost  meanPower  maxPower  ... hourStart  minuteStart  \
0       24.26    0.51  12.37     10.830    22.500  ...        13           20
1       56.19    0.00   0.00     10.996    21.818  ...        15           58
2       17.13    0.76  13.02     10.981    21.818  ...        16            5
3       25.25    0.00   0.00      9.116    21.176  ...        15           58
4       48.09    0.46  22.12      9.006    20.571  ...        16           38
...       ...     ...    ...        ...       ...  ...       ...          ...
12363    5.87    0.00   0.00      2.935     3.600  ...         9           42
12364    9.93    0.00   0.00      3.925     4.360  ...        12           37
12365   11.25    0.27   3.04     -3.516     3.640  ...        18           24
12366   18.81    0.97  18.25      4.324     4.400  ...         9           46
12367    5.59    0.40   2.24     12.918     1.200  ...         7           57

                   endDate  endTimestamp  weekDayEnd  yearEnd hourEnd  \
0      14/09/2019 15:36:26    1568468186           5     2019      15
1      02/09/2019 21:05:12    1567451112           0     2019      21
2      19/09/2019 17:47:08    1568908028           3     2019      17
3      20/11/2019 18:44:21    1574271861           2     2019      18
4      10/10/2019 23:08:14    1570741694           3     2019      23
...                    ...           ...         ...      ...     ...
12363  03/05/2019 12:58:28    1556881108           4     2019      12
12364  23/04/2019 15:09:12    1556024952           1     2019      15
12365  03/10/2019 07:09:00    1570079340           3     2019       7
12366  01/06/2019 14:07:34    1559390854           5     2019      14
12367  21/01/2019 15:59:24    1548082764           0     2019      15

       minuteEnd  anomaly                   class
0             36        0                  Normal
1              5        0                  Normal
2             47        0                  Normal
3             44        0                  Normal
4              8        0                  Normal
...          ...      ...                     ...
12363         58        1  durationSessionAnomaly
12364          9        1  durationSessionAnomaly
12365          9        1        meanPowerAnomaly
12366          7        1   durationChargeAnomaly
12367         59        1        meanPowerAnomaly

[12368 rows x 24 columns]
[0 0 1 ... 1 0 0]
(array([0, 1]), array([7811, 2083]))
(array([0, 1]), array([1953,  521]))
Epoch 1, Loss: 0.3966
Epoch 2, Loss: 0.4652
Epoch 3, Loss: 0.2108
Epoch 4, Loss: 0.2308
Epoch 5, Loss: 0.5522
Epoch 6, Loss: 0.1501
Epoch 7, Loss: 0.0483
Epoch 8, Loss: 0.0838
Surrogate model training complete.
Surrogate Model Results: {'Accuracy': 0.8928860145513339, 'Recall': 0.5067178502879078, 'F1 Score': 0.8792788065428533}
{'connectortype': {'max': np.float64(0.0), 'min': np.float64(0.0), 'mean': np.float64(0.0)}, 'durationcharge': {'max': np.float64(63.97), 'min': np.float64(0.02), 'mean': np.float64(3.0059136481241913)}, 'durationsession': {'max': np.float64(410.09), 'min': np.float64(0.02), 'mean': np.float64(6.094509217335058)}, 'energy': {'max': np.float64(93.929), 'min': np.float64(0.1), 'mean': np.float64(13.631714505174642)}, 'tariff': {'max': np.float64(1.3), 'min': np.float64(0.0), 'mean': np.float64(0.34638826002587325)}, 'cost': {'max': np.float64(87.62), 'min': np.float64(-0.17), 'mean': np.float64(5.131182891332471)}, 'meanpower': {'max': np.float64(36.147), 'min': np.float64(-11.924), 'mean': np.float64(4.852062095730918)}, 'maxpower': {'max': np.float64(22.5), 'min': np.float64(0.167), 'mean': np.float64(5.5840308861578265)}}
[np.float64(0.0), np.float64(0.02), np.float64(0.02), np.float64(0.1), np.float64(0.0), np.float64(-0.17), np.float64(-11.924), np.float64(0.167)]
[np.float64(0.0), np.float64(63.97), np.float64(410.09), np.float64(93.929), np.float64(1.3), np.float64(87.62), np.float64(36.147), np.float64(22.5)]
[0, 1, 1, 1, 1, 1, 1, 1]
Processing file Canada1_clean_WithAnomalies

In [9]:
# Test examples
def read_adv_data(advPath):
    adversarial_data = pd.read_csv(advPath)
    features = [col for col in adversarial_data.columns if col not in ['timestamp', 'anomaly', 'normal/attack',  'startdate', 'weekdaystart', 'yearstart', 'hourstart', 'minutestart', 'enddate', 'endtimestamp', 'weekdayend', 'yearend', 'hourend', 'minuteend', 'class']]
    adversarial_x_data = adversarial_data.loc[:, features].values
    adversarial_y_data = adversarial_data.loc[:, ['anomaly']].values.ravel()
    return adversarial_x_data, adversarial_y_data, features
    
def test_adversarial_samples(advPath, x_test, y_test, model_surrogate, anomalous_indices, device):
    adversarial_x_data, adversarial_y_data, _ = read_adv_data(advPath)
    X_modified, Y_modified  = x_test.clone().cpu().numpy(), y_test.clone().cpu().numpy()
    X_modified[anomalous_indices] = adversarial_x_data
    Y_modified[anomalous_indices] = adversarial_y_data

    try:
        y_pred = model_surrogate.predict(X_modified)
    except: 
        model_surrogate.eval()
        tensor_X_modified = torch.tensor(np.array(X_modified, dtype=np.float32), dtype=torch.float32).to(device)
        with torch.no_grad():
            y_pred = model_surrogate(tensor_X_modified).argmax(axis=1).cpu().numpy()

    accuracy = accuracy_score(Y_modified, y_pred)
    recall = recall_score(Y_modified, y_pred)
    f1 = f1_score(Y_modified, y_pred)
    return  accuracy, f1, recall

def initializeResults(original_results, file_name, epsilons):
    metrics = ["Accuracy", "F1 Score", "Recall", "EIR"]
    attacks = ["MIFGSM"]
    multi_index = pd.MultiIndex.from_product([attacks, metrics], names=["Attack", "Metric"])
    df_results = pd.DataFrame(index=multi_index, columns=epsilons)
    df_results.loc[("MIFGSM", "Accuracy"), 0.0] = original_results[file_name]['results']["Accuracy"]
    df_results.loc[("MIFGSM", "F1 Score"), 0.0] = original_results[file_name]['results']["F1 Score"]
    df_results.loc[("MIFGSM", "Recall"), 0.0] = original_results[file_name]['results']["Recall"]
    df_results.loc[("MIFGSM", "EIR"), 0.0] = "-"
    return df_results

def obtain_adv_results(df_results, original_results, file, stage,  x_test, y_test, anomalous_indices, eps, model_surrogate, device):
    # MIFGSM
    adv_dir = f'./data/aexamples/{file}/mifgsm/{stage}/adversarialexamples_eps{str(eps)}.csv'
    accuracy, f1, recall = test_adversarial_samples(adv_dir, x_test, y_test, model_surrogate, anomalous_indices, device)
    df_results[file].loc[("MIFGSM", "Accuracy"), eps] = accuracy
    df_results[file].loc[("MIFGSM", "F1 Score"), eps] = f1
    df_results[file].loc[("MIFGSM", "Recall"), eps] = recall
    eir = 1 - (df_results[file].loc[("MIFGSM", "Recall"), eps] / max(original_results[file]['results']["Recall"], 1e-8))
    df_results[file].loc[("MIFGSM", "EIR"), eps] = eir * 100

    return df_results

def completeTest(original_results, epsilons, device):
    df_results = {}
    stage = 'test'
    
    for file in original_results:
        df_results[file] = initializeResults(original_results, file, epsilons)
        x_test, y_test = original_results[file]['x_test'], original_results[file]['y_test']
        anomalous_indices = original_results[file]['anomalous_indices_test']
        model_surrogate = original_results[file]['model_surrogate']
        #for value in np.arange(0.003, 0.031, 0.006): 
        #    eps = round(value, 3)
        #    df_results = obtain_adv_results(df_results, file, stage,  x_test, y_test, anomalous_indices, eps, model_surrogate, device)
        
        #for value in np.arange(0.03, 0.3, 0.06):
        for value in np.arange(0.003, 0.031, 0.006): 
            eps = round(value, 3)
            df_results = obtain_adv_results(df_results, original_results, file, stage,  x_test, y_test, anomalous_indices, eps, model_surrogate, device)

        for value in np.arange(0.03, 0.3, 0.06):
            eps = round(value, 3)
            df_results = obtain_adv_results(df_results, original_results, file, stage,  x_test, y_test, anomalous_indices, eps, model_surrogate, device)

    return df_results
df_results = completeTest(original_results, epsilons, device)

In [10]:
import pickle
with open("df_results_gb.pkl", "wb") as f:
    pickle.dump(df_results, f)
with open("original_results_gb.pkl", "wb") as f:
    pickle.dump(original_results, f)

In [ ]:
import pickle
with open("df_results_gb.pkl", "rb") as f:
    df_results = pickle.load(f)
with open("original_results_gb.pkl", "rb") as f:
    original_results = pickle.load(f)

In [11]:
df_results['Dundee_Clean_With_Anomalies_All']

                    0.000     0.003     0.009     0.015     0.021     0.027  \
Attack Metric
MIFGSM Accuracy  0.835855  0.833575  0.831271  0.827352  0.824644  0.821984
       F1 Score  0.828755   0.75935  0.755203  0.748085   0.74312  0.738203
       Recall    0.644492  0.638943  0.633337  0.623801  0.617212  0.610739
       EIR              -  0.860909  1.730786  3.210474  4.232804  5.237198

                    0.030      0.090      0.150     0.210      0.270
Attack Metric
MIFGSM Accuracy  0.821082   0.794528   0.774102  0.759328   0.749139
       F1 Score  0.736525   0.685109   0.642618  0.610134   0.586809
       Recall    0.608542   0.543926    0.49422  0.458271   0.433476
       EIR       5.577975  15.603982  23.316295  28.89427  32.741458

In [12]:
df_results['Dundee_Clean_With_Anomalies']

                    0.000     0.003     0.009     0.015     0.021     0.027  \
Attack Metric
MIFGSM Accuracy  0.823704  0.823144  0.822557  0.821103  0.819705  0.818558
       F1 Score  0.803105  0.610207  0.608406  0.603925   0.59959  0.596015
       Recall    0.459759  0.457909  0.455967  0.451156  0.446531  0.442738
       EIR              -  0.402414   0.82495  1.871227  2.877264  3.702213

                    0.030      0.090      0.150      0.210     0.270
Attack Metric
MIFGSM Accuracy  0.818167   0.802729   0.789921   0.780888  0.775043
       F1 Score   0.59479   0.544727   0.500399   0.467478  0.445394
       Recall    0.441443   0.390379   0.348011   0.318131  0.298797
       EIR       3.983903  15.090543  24.305835  30.804829  35.01006

In [13]:
df_results['Boulder_Clean_With_Anomalies']

                    0.000     0.003     0.009     0.015     0.021     0.027  \
Attack Metric
MIFGSM Accuracy   0.99467   0.99454  0.994151  0.993631  0.993501  0.993241
       F1 Score  0.994633  0.981659  0.980324  0.978537  0.978089  0.977193
       Recall    0.965665  0.964807  0.962232  0.958798   0.95794  0.956223
       EIR              -  0.088889  0.355556  0.711111       0.8  0.977778

                    0.030     0.090     0.150      0.210      0.270
Attack Metric
MIFGSM Accuracy  0.993241  0.988951  0.982192   0.976862   0.972572
       F1 Score  0.977193  0.962172  0.937585   0.917363   0.900519
       Recall    0.956223  0.927897  0.883262   0.848069   0.819742
       EIR       0.977778  3.911111  8.533333  12.177778  15.111111

In [14]:
df_results['PaloAlto_2018_2022_Clean_With_Anomalies']

                    0.000     0.003     0.009     0.015     0.021     0.027  \
Attack Metric
MIFGSM Accuracy  0.978597  0.978176  0.977946  0.977602  0.977104  0.976721
       F1 Score  0.978218  0.926147  0.925311  0.924056  0.922237  0.920833
       Recall    0.889578  0.886849   0.88536  0.883127  0.879901  0.877419
       EIR              -  0.306834  0.474198  0.725244  1.087866  1.366806

                    0.030     0.090      0.150     0.210     0.270
Attack Metric
MIFGSM Accuracy   0.97653  0.970518   0.963588  0.956697  0.950379
       F1 Score   0.92013  0.897579   0.870383  0.841973  0.814645
       Recall    0.876179  0.837221   0.792308  0.747643    0.7067
       EIR       1.506276  5.885635  10.934449  15.95537  20.55788

In [15]:
df_results['Perth_Clean_With_Anomalies']

                    0.000     0.003     0.009     0.015     0.021     0.027  \
Attack Metric
MIFGSM Accuracy  0.988785  0.988148  0.987893  0.986491   0.98579  0.984707
       F1 Score  0.988725  0.961838  0.960986  0.956271  0.953897  0.950207
       Recall    0.951496  0.947454  0.945837  0.936944  0.932498  0.925627
       EIR              -  0.424809  0.594732  1.529312  1.996602  2.718777

                    0.030     0.090     0.150      0.210      0.270
Attack Metric
MIFGSM Accuracy  0.984388  0.975658  0.967183   0.958963   0.952909
       F1 Score  0.949117  0.918341  0.886689   0.854167   0.828975
       Recall    0.923605   0.86823   0.81447   0.762328   0.723929
       EIR       2.931181  8.751062  14.40102  19.881054  23.916737

In [16]:
df_results['Netherlands_Clean_With_Anomalies']

                    0.000     0.003     0.009     0.015     0.021     0.027  \
Attack Metric
MIFGSM Accuracy  0.892886  0.892886  0.892886  0.891673  0.890057  0.889248
       F1 Score  0.879279  0.665826  0.665826  0.660759  0.653944   0.65051
       Recall    0.506718  0.506718  0.506718   0.50096  0.493282  0.489443
       EIR              -       0.0       0.0  1.136364  2.651515  3.409091

                    0.030     0.090      0.150      0.210      0.270
Attack Metric
MIFGSM Accuracy  0.888844  0.883994    0.87793   0.876718   0.874293
       F1 Score  0.648787  0.627756   0.600529   0.594954   0.583668
       Recall    0.487524  0.464491   0.435701   0.429942   0.418426
       EIR       3.787879  8.333333  14.015152  15.151515  17.424242

In [17]:
df_results['Canada1_clean_WithAnomalies']

                    0.000     0.003     0.009     0.015     0.021     0.027  \
Attack Metric
MIFGSM Accuracy  0.956471  0.956429  0.956357    0.9563  0.956271  0.956257
       F1 Score   0.95478  0.879921  0.879701  0.879524  0.879436  0.879392
       Recall    0.800143  0.799928  0.799571  0.799284  0.799141  0.799069
       EIR              -  0.026838  0.071569  0.107354  0.125246  0.134192

                    0.030     0.090     0.150     0.210     0.270
Attack Metric
MIFGSM Accuracy  0.956257  0.955886  0.955557    0.9551  0.954671
       F1 Score  0.879392  0.878243  0.877225  0.875805  0.874471
       Recall    0.799069  0.797208  0.795562  0.793271  0.791124
       EIR       0.134192  0.366792  0.572553   0.85883  1.127214

In [62]:
df_results['Germany_clean_WithAnomalies']

                    0.000     0.003     0.009     0.015     0.021     0.027  \
Attack Metric
MIFGSM Accuracy  0.893157  0.892243  0.891471  0.889986  0.888714  0.887543
       F1 Score  0.886156  0.684591  0.681614  0.675843  0.670864  0.666243
       Recall    0.590551   0.58597  0.582105   0.57466  0.568289  0.562419
       EIR              -  0.775758  1.430303  2.690909  3.769697  4.763636

                    0.030      0.090      0.150      0.210      0.270
Attack Metric
MIFGSM Accuracy  0.887214      0.876   0.865529   0.856057   0.848271
       F1 Score  0.664941   0.618931    0.57301   0.528763   0.490282
       Recall    0.560773   0.504581   0.452112   0.404653   0.365641
       EIR       5.042424  14.557576  23.442424  31.478788  38.084848

In [18]:
df_results['Portugal_clean_WithAnomalies']

                    0.000      0.003     0.009      0.015      0.021  \
Attack Metric
MIFGSM Accuracy  0.914814   0.872814  0.844514   0.823943   0.817143
       F1 Score  0.906554   0.545603  0.382012   0.237942   0.184506
       Recall    0.593057   0.382606  0.240802   0.137724   0.103651
       EIR              -  35.485818   59.3965  76.777308  82.522631

                    0.027     0.030     0.090      0.150      0.210      0.270
Attack Metric
MIFGSM Accuracy  0.819943  0.821286    0.8667   0.870229   0.870343   0.872529
       F1 Score  0.206897   0.21744  0.513123   0.532042   0.532647   0.544117
       Recall    0.117681  0.124409  0.351969   0.369649   0.370222   0.381174
       EIR       80.15691  79.02233  40.65178  37.670489  37.573929  35.727218

In [19]:
df_results['US_Alabama_clean_WithAnomalies']

                    0.000     0.003     0.009     0.015     0.021     0.027  \
Attack Metric
MIFGSM Accuracy  0.934757  0.934143  0.933371  0.932157  0.931057  0.929857
       F1 Score   0.93418  0.830888  0.828567  0.824896   0.82155  0.817878
       Recall    0.813744  0.810666    0.8068  0.800716  0.795204  0.789191
       EIR              -  0.378255  0.853272  1.600985  2.278325  3.017241

                    0.030     0.090      0.150      0.210      0.270
Attack Metric
MIFGSM Accuracy  0.929371  0.918914     0.9098   0.900957   0.892871
       F1 Score  0.816386  0.783309   0.752935   0.721979   0.692298
       Recall    0.786757  0.734359    0.68869   0.644381   0.603865
       EIR       3.316327  9.755454  15.367699  20.812808  25.791696

In [20]:
df_results['vancover_clean_WithAnomalies']

                    0.000     0.003     0.009     0.015     0.021     0.027  \
Attack Metric
MIFGSM Accuracy  0.878843  0.878814  0.878814  0.878814  0.878814  0.878814
       F1 Score  0.860943  0.587944  0.587944  0.587944  0.587944  0.587944
       Recall    0.433357  0.433214  0.433214  0.433214  0.433214  0.433214
       EIR              -  0.033036  0.033036  0.033036  0.033036  0.033036

                    0.030     0.090     0.150     0.210     0.270
Attack Metric
MIFGSM Accuracy  0.878814  0.878743    0.8787  0.878657  0.878586
       F1 Score  0.587944  0.587601  0.587395  0.587189  0.586846
       Recall    0.433214  0.432856  0.432641  0.432427  0.432069
       EIR       0.033036  0.115626   0.16518  0.214734  0.297324

In [21]:
from catboost import CatBoostClassifier
from lightgbm import LGBMClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier

def trainModelsTransfer(x_train, y_train):
    mask = ~torch.isnan(x_train).any(dim=1)
    x_train = x_train[mask]
    y_train = y_train[mask]
    models = []
    # 1. - Train Catboost   
    print("[CATBOOST]")     
    catboost_model = CatBoostClassifier()
    catboost_model.fit(x_train.cpu().numpy(), y_train.cpu().numpy(), verbose=False)
    models.append(catboost_model)
    # 2 . - Train LGBM        
    print("[LGBM]")    
    lgb_model = LGBMClassifier ()
    lgb_model. fit(x_train.cpu().numpy(), y_train.cpu().numpy())
    models.append(lgb_model)
    # 3. - Train MLP
    print("[MLP]")         
    mlp_model = MLPClassifier()
    mlp_model.fit(x_train.cpu().numpy(), y_train.cpu().numpy())
    models.append(mlp_model)
    # 4. - Train RF   
    print("[RF]")      
    rf_model = RandomForestClassifier()
    rf_model.fit(x_train.cpu().numpy(), y_train.cpu().numpy())
    models.append(rf_model)
    # 5. - Train  XGB   
    print("[XGB]")      
    xgb_model = XGBClassifier()
    xgb_model.fit(x_train.cpu().numpy(), y_train.cpu().numpy())
    models.append(xgb_model)
    return models

def initializeResultsTransfer(epsilons, models, x_test, y_test):
    x_test = x_test.cpu().numpy()
    y_test = y_test.cpu().numpy()
    metrics = ["Accuracy", "F1 Score", "Recall", "EIR"]
    attacks = ["MIFGSM"]
    models_names = ["CATBOOST", "LGBM", "MLP", "RF", "XGB"]
    multi_index = pd.MultiIndex.from_product([models_names, attacks, metrics], names=["Models", "Attack", "Metric"])
    df_results = pd.DataFrame(index=multi_index, columns=epsilons)
    for idx, model_name in enumerate(models_names):
        y_pred = models[idx].predict(x_test)
        accuracy = accuracy_score(y_test, y_pred)
        f1 = f1_score(y_test, y_pred)
        recall = recall_score(y_test, y_pred)
        for attack in attacks:
            df_results.loc[(model_name, attack, "Accuracy"), 0.0] = accuracy
            df_results.loc[(model_name, attack, "F1 Score"), 0.0] = f1
            df_results.loc[(model_name, attack, "Recall"), 0.0] = recall
            df_results.loc[(model_name, attack, "EIR"), 0.0] = "-"      

        print(recall)

    return df_results

def test_adversarial_samples_transfer(adv_dir, x_test, y_test, ads_model, anomalous_indices, device):
    adversarial_x_data, adversarial_y_data, _ = read_adv_data(adv_dir)
    X_modified, Y_modified  = x_test.clone().cpu().numpy(), y_test.clone().cpu().numpy()
    X_modified[anomalous_indices] = adversarial_x_data
    Y_modified[anomalous_indices] = adversarial_y_data

    y_pred =  ads_model.predict(X_modified)

    accuracy = accuracy_score(Y_modified, y_pred)
    recall = recall_score(Y_modified, y_pred)
    f1 = f1_score(Y_modified, y_pred)
    print(recall)
    return  accuracy, f1, recall

def obtain_adv_results_transfer(df_results, original_results,  file, stage,  x_test, y_test, anomalous_indices, eps, ads_model, model_name, device):
    # MIFGSM
    adv_dir = f'./data/aexamples/{file}/mifgsm/{stage}/adversarialexamples_eps{str(eps)}.csv'
    accuracy, f1, recall = test_adversarial_samples_transfer(adv_dir, x_test, y_test, ads_model, anomalous_indices, device)
    df_results.loc[(model_name, "MIFGSM", "Accuracy"), eps] = accuracy
    df_results.loc[(model_name,"MIFGSM", "F1 Score"), eps] = f1
    df_results.loc[(model_name,"MIFGSM", "Recall"), eps] = recall
    eir = 1 - (df_results.loc[(model_name,"MIFGSM", "Recall"), eps] / df_results.loc[(model_name,"MIFGSM", "Recall"), 0.0])
    df_results.loc[(model_name,"MIFGSM", "EIR"), eps] = eir * 100
    print(f'Recall: {recall}')
    return df_results
def testTransferability(original_results, epsilons):
    transferability_results = {}
    models_names = ["CATBOOST", "LGBM", "MLP", "RF", "XGB"]
    try_epsilon = [0.0, 0.003, 0.021, 0.090, 0.210]
    # Test normal
    index = 0
    for file in original_results:
        try:
            print(f"processing file {file} number {index}")
            transferability_results[file] = {}
            x_train = original_results[file]['x_train']
            y_train = original_results[file]['y_train']
            x_test = original_results[file]['x_test']
            y_test = original_results[file]['y_test']
            models = trainModelsTransfer(x_train, y_train)
            df_results = initializeResultsTransfer(try_epsilon, models, x_test, y_test)
            transferability_results[file]['models'] = models
            transferability_results[file]['transfer_results'] = df_results
            for idx, model_name in enumerate(models_names):
                for eps in try_epsilon[1:]:
                    transferability_results[file]['transfer_results'] = obtain_adv_results_transfer(transferability_results[file]['transfer_results'] , original_results  , file, 'test',  x_test, y_test, original_results[file]['anomalous_indices_test'], eps, models[idx], model_name, device)
        except Exception as e:
            print(f"File {file} failed because {e}")  
        #if index > 3: 
        #    print(f"Finish with idx {index}")
        #    break
        index = index + 1

# df_results = completeTest(original_results, epsilons, device)
    return transferability_results

In [22]:
transferability_results = testTransferability(original_results, epsilons)

processing file US_Alabama_clean_WithAnomalies number 0
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 56030, number of negative: 223970
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000645 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 280000, number of used features: 2
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.200107 -> initscore=-1.385625
[LightGBM] [Info] Start training from score -1.385625
[MLP]
[RF]
[XGB]
0.8668575518969219
0.8470293486041518
0.7933428775948461
0.888117394416607
0.8629205440229062
0.8635647816750179
Recall: 0.8635647816750179
0.8487473156764496
Recall: 0.8487473156764496
0.7894774516821761
Recall: 0.7894774516821761
0.7052254831782391
Recall: 0.7052254831782391
0.8432355046528275
Recall: 0.8432355046528275
0.8258410880458125
Recall: 0.8258410880458125
0.7707945597709377
Recall: 0.7707945597709377
0.6881889763779527
Recall: 0.6881889763779527
0.7894774516821761
Recall: 0.7894774516821761
0.7764495347172512
Recall: 0.7764495347172512
0.7285612025769506
Recall: 0.7285612025769506
0.6431639226914817
Recall: 0.6431639226914817
0.8838940586972083
Recall: 0.8838940586972083
0.8718682891911238
Recall: 0.8718682891911238
0.8205440229062276
Recall: 0.8205440229062276
0.7439513242662849
Recall: 0.7439513242662849
0.8591982820329277
Recall: 0.8591982820329277
0.8443808160343593
Recall: 0.8443808160343593
0.7856120257695061
Recall: 0.7856120257695061
0.7001431639226915
Recall: 0.7001431639226915
processing file Dundee_Clean_With_Anomalies_All number 1
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 47129, number of negative: 121282
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000780 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1528
[LightGBM] [Info] Number of data points in the train set: 168411, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.279845 -> initscore=-0.945230
[LightGBM] [Info] Start training from score -0.945230
[MLP]
[RF]
[XGB]
0.7640735175124264
0.6376719454398335
0.7527453473586868
0.7427465032944168
0.6968558548144723
0.7622240203444689
Recall: 0.7622240203444689
0.7558663738296151
Recall: 0.7558663738296151
0.7429198936539129
Recall: 0.7429198936539129
0.7639001271529303
Recall: 0.7639001271529303
0.7091665703386891
Recall: 0.7091665703386891
0.6754710438099641
Recall: 0.6754710438099641
0.6388856779563056
Recall: 0.6388856779563056
0.6668593226216623
Recall: 0.6668593226216623
0.7441336261703849
Recall: 0.7441336261703849
0.7486995723037799
Recall: 0.7486995723037799
0.7681770893538319
Recall: 0.7681770893538319
0.7648826725234077
Recall: 0.7648826725234077
0.7387585250260086
Recall: 0.7387585250260086
0.7351173274765923
Recall: 0.7351173274765923
0.7099757253496706
Recall: 0.7099757253496706
0.7502600855392441
Recall: 0.7502600855392441
0.7507802566177321
Recall: 0.7507802566177321
0.7225176280198821
Recall: 0.7225176280198821
0.7212460987169114
Recall: 0.7212460987169114
0.7334412206681309
Recall: 0.7334412206681309
processing file US_Alabama_clean_WithAnomalies_a2 number 2
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 39735, number of negative: 516851
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001148 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 556586, number of used features: 2
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.071391 -> initscore=-2.565522
[LightGBM] [Info] Start training from score -2.565522
[MLP]
[RF]
[XGB]
0.958175329020745
0.9558331474459068
0.94947579745706
0.9745706000446129
0.957840731652911
0.9523756413116217
Recall: 0.9523756413116217
0.9430069150122685
Recall: 0.9430069150122685
0.8875752844077627
Recall: 0.8875752844077627
0.6575953602498327
Recall: 0.6575953602498327
0.9520410439437876
Recall: 0.9520410439437876
0.9490296676332813
Recall: 0.9490296676332813
0.8908097256301584
Recall: 0.8908097256301584
0.6575953602498327
Recall: 0.6575953602498327
0.9472451483381664
Recall: 0.9472451483381664
0.935199643096141
Recall: 0.935199643096141
0.8681686370733883
Recall: 0.8681686370733883
0.603836716484497
Recall: 0.603836716484497
0.94947579745706
Recall: 0.94947579745706
0.9461298237787196
Recall: 0.9461298237787196
0.9142315413785411
Recall: 0.9142315413785411
0.7037697970109302
Recall: 0.7037697970109302
0.9520410439437876
Recall: 0.9520410439437876
0.9424492527325452
Recall: 0.9424492527325452
0.8803256747713585
Recall: 0.8803256747713585
0.660272139192505
Recall: 0.660272139192505
processing file Germany_clean_WithAnomalies_a2 number 3
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 94214, number of negative: 1230818
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.002484 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 1325032, number of used features: 2
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.071103 -> initscore=-2.569865
[LightGBM] [Info] Start training from score -2.569865
[MLP]
[RF]
[XGB]
0.8823746312684366
0.8803466076696165
0.8900719026548672
0.8889196165191741
0.8800700589970502
0.8823746312684366
Recall: 0.8823746312684366
0.8822824483775811
Recall: 0.8822824483775811
0.8821902654867256
Recall: 0.8821902654867256
0.8817754424778761
Recall: 0.8817754424778761
0.8803466076696165
Recall: 0.8803466076696165
0.8803466076696165
Recall: 0.8803466076696165
0.880254424778761
Recall: 0.880254424778761
0.8799317846607669
Recall: 0.8799317846607669
0.8900258112094396
Recall: 0.8900258112094396
0.8899797197640118
Recall: 0.8899797197640118
0.8897953539823009
Recall: 0.8897953539823009
0.8896109882005899
Recall: 0.8896109882005899
0.8888735250737463
Recall: 0.8888735250737463
0.88859697640118
Recall: 0.88859697640118
0.8883665191740413
Recall: 0.8883665191740413
0.8878134218289085
Recall: 0.8878134218289085
0.8800239675516224
Recall: 0.8800239675516224
0.8800239675516224
Recall: 0.8800239675516224
0.879747418879056
Recall: 0.879747418879056
0.8793786873156342
Recall: 0.8793786873156342
processing file Portugal_clean_WithAnomalies_a2 number 4
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 36576, number of negative: 477357
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001384 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 513933, number of used features: 2
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.071169 -> initscore=-2.568872
[LightGBM] [Info] Start training from score -2.568872
[MLP]
[RF]
[XGB]
0.9779191167646706
0.9824792991719669
0.9595583823352934
0.9978399135965439
0.9756390255610224
0.9277571102844113
Recall: 0.9277571102844113
0.8774750990039601
Recall: 0.8774750990039601
0.6471858874354974
Recall: 0.6471858874354974
0.18636745469818794
Recall: 0.18636745469818794
0.8819152766110644
Recall: 0.8819152766110644
0.8376335053402136
Recall: 0.8376335053402136
0.5577823112924517
Recall: 0.5577823112924517
0.1862474498979959
Recall: 0.1862474498979959
0.9339973598943958
Recall: 0.9339973598943958
0.8369134765390616
Recall: 0.8369134765390616
0.5965438617544702
Recall: 0.5965438617544702
0.1827673106924277
Recall: 0.1827673106924277
0.8817952718108725
Recall: 0.8817952718108725
0.8376335053402136
Recall: 0.8376335053402136
0.6584663386535461
Recall: 0.6584663386535461
0.18708748349933998
Recall: 0.18708748349933998
0.9275171006840274
Recall: 0.9275171006840274
0.9468378735149406
Recall: 0.9468378735149406
0.6482659306372255
Recall: 0.6482659306372255
0.18708748349933998
Recall: 0.18708748349933998
processing file vancover_clean_WithAnomalies_a2 number 5
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 23864, number of negative: 311843
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000724 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 335707, number of used features: 2
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.071086 -> initscore=-2.570129
[LightGBM] [Info] Start training from score -2.570129
[MLP]
[RF]
[XGB]
0.7636629501005301
0.6667885212940962
0.5348199597879729
0.8499360263205995
0.6576494242368854
0.7636629501005301
Recall: 0.7636629501005301
0.7631146042770974
Recall: 0.7631146042770974
0.7647596417473953
Recall: 0.7647596417473953
0.7632973862182416
Recall: 0.7632973862182416
0.6667885212940962
Recall: 0.6667885212940962
0.6667885212940962
Recall: 0.6667885212940962
0.6651434838237982
Recall: 0.6651434838237982
0.6698958142935478
Recall: 0.6698958142935478
0.5348199597879729
Recall: 0.5348199597879729
0.5342716139645403
Recall: 0.5342716139645403
0.5337232681411077
Recall: 0.5337232681411077
0.5315298848473771
Recall: 0.5315298848473771
0.8510327179674648
Recall: 0.8510327179674648
0.8497532443794553
Recall: 0.8497532443794553
0.8490221166148785
Recall: 0.8490221166148785
0.8508499360263206
Recall: 0.8508499360263206
0.6622189727654908
Recall: 0.6622189727654908
0.6622189727654908
Recall: 0.6622189727654908
0.661487845000914
Recall: 0.661487845000914
0.6609394991774813
Recall: 0.6609394991774813
processing file Germany_clean_WithAnomalies number 6
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 56030, number of negative: 223970
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.012071 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 280000, number of used features: 2
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.200107 -> initscore=-1.385625
[LightGBM] [Info] Start training from score -1.385625
[MLP]
[RF]
[XGB]
0.6347172512526843
0.6211882605583393
0.5573371510379385
0.6855404438081604
0.6340730136005727
0.6347172512526843
Recall: 0.6347172512526843
0.6347172512526843
Recall: 0.6347172512526843
0.6344309234073013
Recall: 0.6344309234073013
0.6339298496778811
Recall: 0.6339298496778811
0.6211166785969936
Recall: 0.6211166785969936
0.6211166785969936
Recall: 0.6211166785969936
0.6210450966356478
Recall: 0.6210450966356478
0.6210450966356478
Recall: 0.6210450966356478
0.5573371510379385
Recall: 0.5573371510379385
0.5573371510379385
Recall: 0.5573371510379385
0.5573371510379385
Recall: 0.5573371510379385
0.5571224051539012
Recall: 0.5571224051539012
0.6853972798854688
Recall: 0.6853972798854688
0.6851825340014316
Recall: 0.6851825340014316
0.6848246241947029
Recall: 0.6848246241947029
0.6847530422333572
Recall: 0.6847530422333572
0.6340730136005727
Recall: 0.6340730136005727
0.6340730136005727
Recall: 0.6340730136005727
0.6342161775232641
Recall: 0.6342161775232641
0.6337866857551897
Recall: 0.6337866857551897
processing file Canada1_clean_WithAnomalies_a2 number 7
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 849445, number of negative: 11094491
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.232898 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 506
[LightGBM] [Info] Number of data points in the train set: 11943936, number of used features: 2
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.071119 -> initscore=-2.569621
[LightGBM] [Info] Start training from score -2.569621
[MLP]
[RF]
[XGB]
0.9779365541773355
0.9681595396165856
0.8151822265834624
0.981570353107128
0.954953159258521
0.9778854458942161
Recall: 0.9778854458942161
0.9552087006741182
Recall: 0.9552087006741182
0.9528168330241282
Recall: 0.9528168330241282
0.9730454914828046
Recall: 0.9730454914828046
0.9779212216923997
Recall: 0.9779212216923997
0.977435693002765
Recall: 0.977435693002765
0.9646484005662798
Recall: 0.9646484005662798
0.962322973684345
Recall: 0.962322973684345
0.8003352703372636
Recall: 0.8003352703372636
0.7935583119956251
Recall: 0.7935583119956251
0.7872873256568692
Recall: 0.7872873256568692
0.798168279132999
Recall: 0.798168279132999
0.9814579148842653
Recall: 0.9814579148842653
0.9586329556431211
Recall: 0.9586329556431211
0.9562666421346908
Recall: 0.9562666421346908
0.9765975171596061
Recall: 0.9765975171596061
0.9613365838201398
Recall: 0.9613365838201398
0.9592462550405544
Recall: 0.9592462550405544
0.9430909267464979
Recall: 0.9430909267464979
0.9390124857535661
Recall: 0.9390124857535661
processing file Netherlands_Clean_With_Anomalies number 8
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 2083, number of negative: 7811
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000424 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1651
[LightGBM] [Info] Number of data points in the train set: 9894, number of used features: 7
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.210532 -> initscore=-1.321724
[LightGBM] [Info] Start training from score -1.321724
[MLP]
[RF]
[XGB]
0.7216890595009597
0.7178502879078695
0.7735124760076776
0.6679462571976967
0.7389635316698656
0.7197696737044146
Recall: 0.7197696737044146
0.7485604606525912
Recall: 0.7485604606525912
0.710172744721689
Recall: 0.710172744721689
0.6007677543186181
Recall: 0.6007677543186181
0.7543186180422264
Recall: 0.7543186180422264
0.7485604606525912
Recall: 0.7485604606525912
0.6967370441458733
Recall: 0.6967370441458733
0.6967370441458733
Recall: 0.6967370441458733
0.7696737044145874
Recall: 0.7696737044145874
0.7581573896353166
Recall: 0.7581573896353166
0.7120921305182342
Recall: 0.7120921305182342
0.6353166986564299
Recall: 0.6353166986564299
0.6756238003838771
Recall: 0.6756238003838771
0.7370441458733206
Recall: 0.7370441458733206
0.7140115163147792
Recall: 0.7140115163147792
0.654510556621881
Recall: 0.654510556621881
0.800383877159309
Recall: 0.800383877159309
0.7850287907869482
Recall: 0.7850287907869482
0.783109404990403
Recall: 0.783109404990403
0.6890595009596929
Recall: 0.6890595009596929
processing file Canada1_clean_WithAnomalies number 9
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 56030, number of negative: 223970
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000606 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 510
[LightGBM] [Info] Number of data points in the train set: 280000, number of used features: 2
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.200107 -> initscore=-1.385625
[LightGBM] [Info] Start training from score -1.385625
[MLP]
[RF]
[XGB]
0.9972798854688618
0.9933428775948461
0.9111667859699356
0.9973514674302076
0.9841803865425912
0.9971367215461704
Recall: 0.9971367215461704
0.9972798854688618
Recall: 0.9972798854688618
0.9969935576234789
Recall: 0.9969935576234789
0.9971367215461704
Recall: 0.9971367215461704
0.9931997136721546
Recall: 0.9931997136721546
0.9926986399427344
Recall: 0.9926986399427344
0.9928418038654259
Recall: 0.9928418038654259
0.9928418038654259
Recall: 0.9928418038654259
0.9110952040085898
Recall: 0.9110952040085898
0.9108804581245526
Recall: 0.9108804581245526
0.9093056549749463
Recall: 0.9093056549749463
0.9057981388690051
Recall: 0.9057981388690051
0.9971367215461704
Recall: 0.9971367215461704
0.9972798854688618
Recall: 0.9972798854688618
0.9969935576234789
Recall: 0.9969935576234789
0.9970651395848247
Recall: 0.9970651395848247
0.9843235504652827
Recall: 0.9843235504652827
0.9841088045812455
Recall: 0.9841088045812455
0.9839656406585541
Recall: 0.9839656406585541
0.9832498210450966
Recall: 0.9832498210450966
processing file Boulder_Clean_With_Anomalies number 10
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 4695, number of negative: 26074
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000795 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1397
[LightGBM] [Info] Number of data points in the train set: 30769, number of used features: 6
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.152589 -> initscore=-1.714441
[LightGBM] [Info] Start training from score -1.714441
[MLP]
[RF]
[XGB]
0.9682403433476395
0.9484978540772532
0.9836909871244636
0.9201716738197425
0.9605150214592275
0.9665236051502146
Recall: 0.9665236051502146
0.9682403433476395
Recall: 0.9682403433476395
0.9476394849785408
Recall: 0.9476394849785408
0.8489270386266095
Recall: 0.8489270386266095
0.9184549356223176
Recall: 0.9184549356223176
0.9072961373390558
Recall: 0.9072961373390558
0.8909871244635194
Recall: 0.8909871244635194
0.8566523605150215
Recall: 0.8566523605150215
0.9828326180257511
Recall: 0.9828326180257511
0.9716738197424892
Recall: 0.9716738197424892
0.9476394849785408
Recall: 0.9476394849785408
0.8781115879828326
Recall: 0.8781115879828326
0.91931330472103
Recall: 0.91931330472103
0.9304721030042918
Recall: 0.9304721030042918
0.886695278969957
Recall: 0.886695278969957
0.8231759656652361
Recall: 0.8231759656652361
0.9690987124463519
Recall: 0.9690987124463519
0.9665236051502146
Recall: 0.9665236051502146
0.9459227467811159
Recall: 0.9459227467811159
0.8154506437768241
Recall: 0.8154506437768241
processing file Perth_Clean_With_Anomalies number 11
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 9818, number of negative: 52951
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.001803 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1403
[LightGBM] [Info] Number of data points in the train set: 62769, number of used features: 8
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.156415 -> initscore=-1.685150
[LightGBM] [Info] Start training from score -1.685150
[MLP]
[RF]
[XGB]
0.9611964430072757
0.9139046079223929
0.9518997574777688
0.9066289409862571
0.9498787388843978
0.9640258690379951
Recall: 0.9640258690379951
0.9700889248181084
Recall: 0.9700889248181084
0.9393694421988682
Recall: 0.9393694421988682
0.8573160873080032
Recall: 0.8573160873080032
0.9009700889248181
Recall: 0.9009700889248181
0.8908649959579629
Recall: 0.8908649959579629
0.8746968472109944
Recall: 0.8746968472109944
0.8451899757477769
Recall: 0.8451899757477769
0.9514955537590946
Recall: 0.9514955537590946
0.944624090541633
Recall: 0.944624090541633
0.9078415521422797
Recall: 0.9078415521422797
0.8379143088116411
Recall: 0.8379143088116411
0.9094583670169766
Recall: 0.9094583670169766
0.9236054971705739
Recall: 0.9236054971705739
0.8908649959579629
Recall: 0.8908649959579629
0.8160873080032336
Recall: 0.8160873080032336
0.9640258690379951
Recall: 0.9640258690379951
0.9668552950687146
Recall: 0.9668552950687146
0.9454324979789814
Recall: 0.9454324979789814
0.8439773645917542
Recall: 0.8439773645917542
processing file PaloAlto_2018_2022_Clean_With_Anomalies number 12
[CATBOOST]
[LGBM]
[LightGBM] [Info] Number of positive: 15956, number of negative: 88515
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000513 seconds.
You can set `force_row_wise=true` to remove the overhead.

In [23]:
import pickle
with open("transferability_results_gb.pkl", "wb") as f:
    pickle.dump(transferability_results, f)

In [ ]:
import pickle
with open("transferability_results_gb.pkl", "rb") as f:
    transferability_results = pickle.load(f)

In [24]:
transferability_results['Dundee_Clean_With_Anomalies']['transfer_results']

                             0.000     0.003      0.021      0.090      0.210
Models   Attack Metric
CATBOOST MIFGSM Accuracy  0.886347  0.882823   0.855445   0.828318   0.802813
                F1 Score  0.780087  0.771712   0.702504   0.625785   0.544891
                Recall     0.66679  0.655134    0.56457   0.474838   0.390472
                EIR              -  1.748058  15.330189  28.787458  41.440067
LGBM     MIFGSM Accuracy  0.855557  0.855025   0.843615    0.82197   0.793808
                F1 Score  0.700389  0.698955    0.66738   0.603068    0.50948
                Recall    0.558464  0.556707   0.518964   0.447364   0.354209
                EIR              -  0.314726    7.07305  19.893987  36.574458
MLP      MIFGSM Accuracy  0.824543  0.823844   0.820935   0.811567   0.798674
                F1 Score  0.617765  0.615657   0.606816   0.577555   0.535219
                Recall     0.46901  0.466698   0.457077   0.426087   0.383441
                EIR              -  0.493097   2.544379   9.151874  18.244576
RF       MIFGSM Accuracy  0.835589   0.83008    0.80726   0.790145   0.767017
                F1 Score  0.668583  0.653631   0.587947   0.534318   0.455027
                Recall    0.548566  0.530342   0.454857   0.398242   0.321739
                EIR              -  3.322091  17.082631  27.403035  41.349073
XGB      MIFGSM Accuracy  0.859025  0.868393   0.853375   0.829772   0.802981
                F1 Score  0.710803  0.735112   0.695688   0.628502   0.543333
                Recall     0.57308   0.60407   0.554394   0.476318   0.387697
                EIR              - -5.407587   3.260694  16.884584  32.348668

In [25]:
transferability_results['PaloAlto_2018_2022_Clean_With_Anomalies']['transfer_results']

                             0.000     0.003     0.021     0.090      0.210
Models   Attack Metric
CATBOOST MIFGSM Accuracy   0.98189  0.981698   0.98055  0.971667   0.955854
                F1 Score  0.940089  0.939417  0.935369  0.902989   0.840194
                Recall    0.920844  0.919603  0.912159  0.854591   0.752109
                EIR              -  0.134735  0.943142  7.194826  18.323902
LGBM     MIFGSM Accuracy  0.977142   0.97718  0.975764  0.967609    0.95214
                F1 Score  0.923294  0.923433  0.918291  0.887709   0.824684
                Recall    0.891563  0.891811   0.88263  0.829777   0.729529
                EIR              - -0.027832  1.001948  6.930142  18.174228
MLP      MIFGSM Accuracy  0.981086   0.98078  0.979746  0.973581    0.96378
                F1 Score  0.936812  0.935723  0.932031  0.909473   0.871572
                Recall    0.908685    0.9067       0.9   0.86005   0.796526
                EIR              -   0.21846  0.955762  5.352267  12.342982
RF       MIFGSM Accuracy   0.98055   0.98032   0.97875  0.969217   0.954246
                F1 Score  0.935517  0.934705  0.929128  0.893959    0.83382
                Recall    0.914392  0.912903   0.90273  0.840943   0.743921
                EIR              -  0.162822  1.275441  8.032564  18.643148
XGB      MIFGSM Accuracy  0.980014  0.979822  0.978099  0.971131   0.956811
                F1 Score  0.933452  0.932772   0.92661  0.900946   0.844156
                Recall    0.908437  0.907196   0.89603  0.850868   0.758065
                EIR              -  0.136575  1.365747  6.337066  16.552854

In [26]:
transferability_results['Netherlands_Clean_With_Anomalies']['transfer_results']

                             0.000     0.003      0.021     0.090      0.210
Models   Attack Metric
CATBOOST MIFGSM Accuracy   0.93654  0.936136   0.942199  0.934115   0.911075
                F1 Score  0.827283  0.825991    0.84507  0.819491   0.739953
                Recall    0.721689   0.71977    0.74856  0.710173   0.600768
                EIR              -  0.265957  -3.723404  1.595745  16.755319
LGBM     MIFGSM Accuracy  0.934519  0.942199   0.940986  0.930073   0.930073
                F1 Score  0.821978  0.846071   0.842333  0.807564   0.807564
                Recall     0.71785  0.754319    0.74856  0.696737   0.696737
                EIR              - -5.080214  -4.278075  2.941176   2.941176
MLP      MIFGSM Accuracy  0.935327  0.934519   0.932094  0.922393   0.906225
                F1 Score  0.834369   0.83195   0.824635  0.794433   0.740492
                Recall    0.773512  0.769674   0.758157  0.712092   0.635317
                EIR              -  0.496278   1.985112  7.940447  17.866005
RF       MIFGSM Accuracy  0.923201  0.924818   0.937753  0.932902   0.920372
                F1 Score  0.785553  0.791011   0.832972  0.817582   0.775882
                Recall    0.667946  0.675624   0.737044  0.714012   0.654511
                EIR              - -1.149425 -10.344828 -6.896552   2.011494
XGB      MIFGSM Accuracy  0.937753  0.950687   0.947454  0.947049   0.927243
                F1 Score  0.833333  0.872385   0.862869  0.861668   0.799555
                Recall    0.738964  0.800384   0.785029  0.783109    0.68906
                EIR              - -8.311688  -6.233766 -5.974026   6.753247

In [27]:
transferability_results['Boulder_Clean_With_Anomalies']['transfer_results']

                             0.000     0.003     0.021     0.090      0.210
Models   Attack Metric
CATBOOST MIFGSM Accuracy   0.99506    0.9948   0.99506  0.991941   0.976992
                F1 Score  0.983435  0.982548  0.983435  0.972687   0.917865
                Recall     0.96824  0.966524   0.96824  0.947639   0.848927
                EIR              -  0.177305       0.0   2.12766  12.322695
LGBM     MIFGSM Accuracy  0.992201  0.987651  0.985961  0.983491   0.978292
                F1 Score  0.973568  0.957494  0.951395  0.942351   0.922792
                Recall    0.948498  0.918455  0.907296  0.890987   0.856652
                EIR              -  3.167421  4.343891  6.063348   9.683258
MLP      MIFGSM Accuracy   0.99714   0.99701   0.99532  0.991681   0.981152
                F1 Score  0.990493  0.990056  0.984348  0.971831    0.93382
                Recall    0.983691  0.982833  0.971674  0.947639   0.878112
                EIR              -   0.08726   1.22164  3.664921  10.732984
RF       MIFGSM Accuracy  0.987911  0.987781  0.989471  0.982842   0.973222
                F1 Score  0.958426  0.957961  0.963984  0.939945   0.903013
                Recall    0.920172  0.919313  0.930472  0.886695   0.823176
                EIR              -  0.093284 -1.119403   3.63806  10.541045
XGB      MIFGSM Accuracy  0.993891   0.99519    0.9948  0.991681   0.971923
                F1 Score  0.979431  0.983878  0.982548  0.971781   0.897921
                Recall    0.960515  0.969099  0.966524  0.945923   0.815451
                EIR              - -0.893655 -0.625559  1.519214   15.10277

In [28]:
transferability_results['Perth_Clean_With_Anomalies']['transfer_results']

                             0.000     0.003     0.021     0.090      0.210
Models   Attack Metric
CATBOOST MIFGSM Accuracy  0.993628  0.994074   0.99503  0.990187   0.977251
                F1 Score  0.979407  0.980876   0.98401   0.96793   0.922374
                Recall    0.961196  0.964026  0.970089  0.939369   0.857316
                EIR              - -0.294365 -0.925147  2.270816  10.807401
LGBM     MIFGSM Accuracy   0.98528  0.983241  0.981648  0.979099   0.974447
                F1 Score  0.951399  0.944291  0.938671  0.929553   0.912503
                Recall    0.913905   0.90097  0.890865  0.874697    0.84519
                EIR              -  1.415303  2.521008  4.290137   7.518797
MLP      MIFGSM Accuracy  0.991461  0.991397  0.990314  0.984515   0.973491
                F1 Score  0.972337  0.972125  0.968504   0.94868   0.908812
                Recall      0.9519  0.951496  0.944624  0.907842   0.837914
                EIR              -  0.042463  0.764331   4.62845  11.974522
RF       MIFGSM Accuracy  0.985025  0.985471  0.987702   0.98254   0.970751
                F1 Score  0.950222  0.951777  0.959479  0.941478   0.897932
                Recall    0.906629  0.909458  0.923605  0.890865   0.816087
                EIR              - -0.312082 -1.872492  1.738743   9.986625
XGB      MIFGSM Accuracy  0.991907  0.994138  0.994584  0.991206   0.975212
                F1 Score   0.97369  0.981078  0.982543  0.971346   0.914786
                Recall    0.949879  0.964026  0.966855  0.945432   0.843977
                EIR              - -1.489362 -1.787234  0.468085  11.148936

In [29]:
transferability_results['US_Alabama_clean_WithAnomalies']['transfer_results']

                             0.000     0.003     0.021     0.090      0.210
Models   Attack Metric
CATBOOST MIFGSM Accuracy  0.917129  0.916471  0.913514  0.901686   0.884871
                F1 Score  0.806769  0.804937  0.796627  0.762198   0.709722
                Recall    0.866858  0.863565  0.848747  0.789477   0.705225
                EIR              -  0.379851  2.089182  8.926507  18.645747
LGBM     MIFGSM Accuracy  0.921886  0.921129  0.917657  0.906671   0.890186
                F1 Score  0.812316  0.810151  0.800125  0.767252   0.714397
                Recall    0.847029  0.843236  0.825841  0.770795   0.688189
                EIR              -    0.4479  2.501479  9.000254  18.752641
MLP      MIFGSM Accuracy  0.933086  0.932314  0.929714  0.920157   0.903114
                F1 Score  0.825549  0.823183  0.815135  0.784583   0.726002
                Recall    0.793343  0.789477   0.77645  0.728561   0.643164
                EIR              -  0.487233  2.129387  8.165659  18.929893
RF       MIFGSM Accuracy    0.8936  0.892757  0.890357  0.880114   0.864829
                F1 Score   0.76914  0.766885  0.760418  0.732039   0.687186
                Recall    0.888117  0.883894  0.871868  0.820544   0.743951
                EIR              -  0.475538  1.829612  7.608608  16.232772
XGB      MIFGSM Accuracy  0.910857  0.910114  0.907157  0.895429   0.878371
                F1 Score  0.794399   0.79233  0.784022  0.749915   0.696752
                Recall    0.862921  0.859198  0.844381  0.785612   0.700143
                EIR              -  0.431356  2.148486  8.958938  18.863542

In [30]:
transferability_results['Germany_clean_WithAnomalies']['transfer_results']

                             0.000     0.003     0.021     0.090     0.210
Models   Attack Metric
CATBOOST MIFGSM Accuracy  0.893529  0.893529  0.893529  0.893471  0.893371
                F1 Score  0.704093  0.704093  0.704093  0.703888  0.703527
                Recall    0.634717  0.634717  0.634717  0.634431   0.63393
                EIR              -       0.0       0.0  0.045111  0.124055
LGBM     MIFGSM Accuracy  0.894871  0.894857  0.894857  0.894843  0.894843
                F1 Score  0.702246  0.702193  0.702193  0.702141  0.702141
                Recall    0.621188  0.621117  0.621117  0.621045  0.621045
                EIR              -  0.011523  0.011523  0.023047  0.023047
MLP      MIFGSM Accuracy  0.876229  0.876229  0.876229  0.876229  0.876186
                F1 Score  0.642515  0.642515  0.642515  0.642515  0.642347
                Recall    0.557337  0.557337  0.557337  0.557337  0.557122
                EIR              -       0.0       0.0       0.0  0.038531
RF       MIFGSM Accuracy    0.8645  0.864471  0.864429  0.864357  0.864343
                F1 Score  0.668808  0.668715  0.668576  0.668343  0.668297
                Recall     0.68554  0.685397  0.685183  0.684825  0.684753
                EIR              -  0.020883  0.052208  0.104417  0.114859
XGB      MIFGSM Accuracy  0.893371  0.893371  0.893371    0.8934  0.893314
                F1 Score  0.703574  0.703574  0.703574  0.703677  0.703368
                Recall    0.634073  0.634073  0.634073  0.634216  0.633787
                EIR              -       0.0       0.0 -0.022578  0.045157

In [31]:
transferability_results['Canada1_clean_WithAnomalies']['transfer_results']

                             0.000     0.003     0.021     0.090     0.210
Models   Attack Metric
CATBOOST MIFGSM Accuracy  0.996443  0.996414  0.996443  0.996386  0.996414
                F1 Score  0.991143  0.991071  0.991143  0.990999  0.991071
                Recall     0.99728  0.997137   0.99728  0.996994  0.997137
                EIR              -  0.014355       0.0  0.028711  0.014355
LGBM     MIFGSM Accuracy  0.997286  0.997257  0.997157  0.997186  0.997186
                F1 Score  0.993201  0.993129  0.992876  0.992948  0.992948
                Recall    0.993343    0.9932  0.992699  0.992842  0.992842
                EIR              -  0.014412  0.064856  0.050443  0.050443
MLP      MIFGSM Accuracy  0.967871  0.967857  0.967814    0.9675    0.9668
                F1 Score  0.918829   0.91879  0.918673  0.917814  0.915895
                Recall    0.911167  0.911095   0.91088  0.909306  0.905798
                EIR              -  0.007856  0.031424  0.204258  0.589206
RF       MIFGSM Accuracy  0.994343    0.9943  0.994329  0.994271  0.994286
                F1 Score  0.985988  0.985881  0.985952  0.985809  0.985845
                Recall    0.997351  0.997137   0.99728  0.996994  0.997065
                EIR              -  0.021532  0.007177  0.035886  0.028709
XGB      MIFGSM Accuracy  0.984557  0.984586  0.984543  0.984514  0.984371
                F1 Score  0.962175  0.962248  0.962139  0.962066  0.961703
                Recall     0.98418  0.984324  0.984109  0.983966   0.98325
                EIR              - -0.014547  0.007273   0.02182  0.094552

In [32]:
transferability_results['vancover_clean_WithAnomalies']['transfer_results']

                             0.000     0.003     0.021     0.090     0.210
Models   Attack Metric
CATBOOST MIFGSM Accuracy  0.918914  0.918857  0.918829  0.918871  0.918929
                F1 Score  0.786633   0.78645  0.786359  0.786496  0.786678
                Recall    0.748962  0.748676  0.748533  0.748747  0.749034
                EIR              -   0.03823  0.057345  0.028672 -0.009557
LGBM     MIFGSM Accuracy  0.900314  0.900286  0.900271  0.900286  0.899943
                F1 Score  0.722985  0.722884  0.722833  0.722884  0.721666
                Recall    0.651825  0.651682  0.651611  0.651682  0.649964
                EIR              -  0.021964  0.032945  0.021964  0.285526
MLP      MIFGSM Accuracy  0.872829  0.872829  0.872829  0.872814  0.872729
                F1 Score   0.61967   0.61967   0.61967  0.619611  0.619257
                Recall    0.519112  0.519112  0.519112  0.519041  0.518611
                EIR              -       0.0       0.0  0.013789  0.096525
RF       MIFGSM Accuracy  0.916486  0.916486  0.916586  0.916543  0.916471
                F1 Score  0.785231  0.785231  0.785544   0.78541  0.785187
                Recall    0.764996  0.764996  0.765497  0.765283  0.764925
                EIR              -       0.0   -0.0655 -0.037429  0.009357
XGB      MIFGSM Accuracy    0.8815    0.8815  0.881486    0.8815  0.881514
                F1 Score  0.670663  0.670663  0.670611  0.670663  0.670716
                Recall    0.604581  0.604581   0.60451  0.604581  0.604653
                EIR              -       0.0   0.01184       0.0  -0.01184

In [33]:
transferability_results['Portugal_clean_WithAnomalies']['transfer_results']

                             0.000      0.003      0.021      0.090      0.210
Models   Attack Metric
CATBOOST MIFGSM Accuracy  0.926786   0.894857   0.858071   0.884171   0.892171
                F1 Score  0.804307   0.692744   0.535292   0.650608   0.682403
                Recall    0.753901   0.593916   0.409592   0.540372   0.580458
                EIR              -  21.221041  45.670338  28.323205  23.006077
LGBM     MIFGSM Accuracy  0.926343   0.892743   0.852171   0.879457   0.886186
                F1 Score  0.798877   0.677547   0.493837   0.622528   0.650953
                Recall    0.732999   0.564639   0.361346   0.498067   0.531782
                EIR              -   22.96875  50.703125  32.050781  27.451172
MLP      MIFGSM Accuracy  0.914557   0.874814   0.810829   0.855657   0.870829
                F1 Score  0.740689   0.567963   0.162111   0.466582    0.54799
                Recall    0.611453   0.412312   0.091696   0.316321   0.392341
                EIR              -  32.568485  85.003512  48.267385  35.834699
RF       MIFGSM Accuracy  0.916286   0.897814   0.870114   0.889386   0.895657
                F1 Score  0.798778   0.742966   0.648822   0.715738   0.736108
                Recall     0.83257   0.740014   0.601217   0.697781   0.729205
                EIR              -  11.116843  27.787808  16.189494  12.415098
XGB      MIFGSM Accuracy  0.926457   0.899329   0.865871     0.8877   0.891543
                F1 Score  0.804229   0.711153   0.574292   0.666667   0.681704
                Recall    0.756908   0.620974   0.453329   0.562706   0.581961
                EIR              -  17.959145  40.107812  25.657273  23.113297